{
 "title": "enmon",
 "time": { "from": "now/fy", "to": "now/fy" },
 "templating": {
  "list": [
   {
    "name": "enmon_id",
    "label": "Plant",
    "query": "SHOW TAG VALUES ON \"enmon\" WITH KEY = \"enmon_id\""
   }
  ]
 },
 "panels": [
  { "title": "Present data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily energy usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Power consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"meter_generation\") + mean(\"meter_battery\") + mean(\"meter_grid\")\nFROM \"autogen\".\"enmon\"\nWHERE \"enmon_id\"::tag =~ /^$enmon_id$/ AND $timeFilter\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Power production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enmon",
     "query": "SELECT mean(\"meter_generation\") FROM \"autogen\".\"enmon\" WHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "meter_generation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "enmon_id::tag", "operator": "=~", "value": "/^$enmon_id$/" }
     ]
    },
    {
     "alias": "Battery charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enmon",
     "query": "SELECT mean(\"to_battery\")\nFROM (\n    SELECT ((ABS(\"meter_battery\") - \"meter_battery\") / 2) AS \"to_battery\"\n    FROM \"autogen\".\"enmon\"\n    WHERE \"enmon_id\"::tag =~ /^$enmon_id$/ AND $timeFilter\n)\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "meter_battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "enmon_id::tag", "operator": "=~", "value": "/^$enmon_id$/" },
      { "condition": "AND", "key": "meter_battery::field", "operator": "<", "value": "0" }
     ]
    },
    {
     "alias": "Battery discharge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enmon",
     "query": "SELECT mean(\"from_battery\")\nFROM (\n    SELECT ((ABS(\"meter_battery\") + \"meter_battery\") / 2) AS \"from_battery\"\n    FROM \"autogen\".\"enmon\"\n    WHERE \"enmon_id\"::tag =~ /^$enmon_id$/ AND $timeFilter\n)\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "meter_generation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "enmon_id::tag", "operator": "=~", "value": "/^$enmon_id$/" },
      { "condition": "AND", "key": "meter_grid", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "alias": "Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enmon",
     "select": [
      [
       { "params": [ "percentage_battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "enmon_id::tag", "operator": "=~", "value": "/^$enmon_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Current consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "enmon",
     "query": "SELECT LAST(\"meter_generation\") + LAST(\"meter_battery\") + LAST(\"meter_grid\")\nFROM \"autogen\".\"enmon\"\nWHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "enmon_id::tag", "operator": "=~", "value": "/^$enmon_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery temperature",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enmon",
     "query": "SELECT last(\"temperature_battery\") FROM \"autogen\".\"enmon\" WHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "percentage_battery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "enmon_id::tag", "operator": "=~", "value": "/^$enmon_id$/" }
     ]
    }
   ]
  },
  { "title": "Historical data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Energy usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Total energy consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enmon",
     "query": "SELECT SUM(\"consumed_hour\")\nFROM (\n    SELECT \"time\", MEAN(\"meter_generation\") + MEAN(\"meter_grid\") + MEAN(\"meter_battery\") AS \"consumed_hour\"\n    FROM \"autogen\".\"enmon\"\n    WHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND $timeFilter\n    GROUP BY TIME(1h) FILL(0)\n)\nGROUP BY TIME($__interval)",
     "select": [
      [
       {
        "params": [
         "abs(\"meter_grid\")"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "enmon_id::tag", "operator": "=~", "value": "/^$enmon_id$/" }
     ]
    },
    {
     "alias": "Total energy produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"produced_hour\")\nFROM (\n    SELECT \"time\", MEAN(\"meter_generation\") AS \"produced_hour\"\n    FROM \"autogen\".\"enmon\"\n    WHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND $timeFilter\n    GROUP BY TIME(1h) FILL(0)\n)\nGROUP BY TIME($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid imports",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nSELECT SUM(\"imported_hour\")\nFROM (\n    SELECT \"time\", MEAN(\"meter_grid\") AS \"imported_hour\"\n    FROM \"autogen\".\"enmon\"\n    WHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND \"meter_grid\" > 0 AND $timeFilter\n    GROUP BY TIME(1h) FILL(0)\n)\nGROUP BY TIME($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Generated energy utilization",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exported to grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enmon",
     "query": "SELECT SUM(\"to_grid_hour\")\nFROM (\n    SELECT MEAN(\"to_grid\") AS \"to_grid_hour\"\n    FROM (\n        SELECT ((ABS(\"meter_grid\") - \"meter_grid\") / 2) AS \"to_grid\"\n        FROM \"autogen\".\"enmon\"\n        WHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND $timeFilter\n    )\n    GROUP BY TIME(1h) FILL(0)\n)",
     "select": [
      [
       {
        "params": [
         "abs(\"meter_grid\")"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "enmon_id::tag", "operator": "=~", "value": "/^$enmon_id$/" }
     ]
    },
    {
     "alias": "Charged",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"to_battery_hour\")\nFROM (\n    SELECT MEAN(\"to_battery\") AS \"to_battery_hour\"\n    FROM (\n        SELECT ((ABS(\"meter_battery\") - \"meter_battery\") / 2) AS \"to_battery\"\n        FROM \"autogen\".\"enmon\"\n        WHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND $timeFilter\n    )\n    GROUP BY TIME(1h) FILL(0)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total energy produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"produced_hour\")\nFROM (\n    SELECT MEAN(\"meter_generation\") AS \"produced_hour\"\n    FROM \"autogen\".\"enmon\"\n    WHERE (\"enmon_id\"::tag =~ /^$enmon_id$/) AND $timeFilter\n    GROUP BY TIME(1h) FILL(0)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$energy_produced - $energy_to_battery - $energy_to_grid",
     "type": "math"
    }
   ]
  }
 ]
}